---
#  The interface where the all servers listen: nrpe, mysql and other
iface: '{{ ansible_default_ipv4.interface }}'
ifaddr: '{{ ansible_default_ipv4.address }}'

# monitoring disable|enable
monitoring_status: disable
# monitoring server address
# monitoring_server: lzxxvqgcqg.local
monitoring_server_netaddr: 155.212.130.155
monitoring_server: lzxxvqgcqg.local

# cluster configuration for sites
cluster_web_configure: disable
cluster_web_server: lzxxvqgcqg.local
cluster_web_netaddr: 155.212.130.155

# configure iptables in common role: disable|enable
iptables_configure: enable

# amazon cloud or generic installation: generic|amazon
pool_installation: generic

# default redis passwords for transformer/rabbitmq integration
redis_password: "red1s"
redis_root_password: "red1s"
