upstream push_sub {
ip_hash;
    keepalive 1024;
    server push_server:8010;
    server push_server:8011;
    server push_server:8012;
    server push_server:8013;
    server push_server:8014;
    server push_server:8015;
}

upstream push_pub {
    ip_hash;
    keepalive 1024;
    server push_server:9010;
    server push_server:9011;
}
