---
- set_fact:
    manage: "{{ manage | default('configure_nodejs') }}"
    hostname: "{{ hostname | default(inventory_hostname) }}"
    push_server: "{{ push_server | default(inventory_hostname) }}"
    bx_netaddr: "{{ bx_netaddr | default(ansible_default_ipv4.address | default('127.0.0.1')) }}"

- debug:
    msg: "{{ ansible_playbook_file }}"

- name: include variables from temporary config
  include_vars:
    file: "{{ ansible_playbook_file }}"
  when: "ansible_playbook_file != 'NOT_DEFINED'"

- name: additional gathering facts
  bx_vat: 

- debug:
    msg: "manage = {{ manage }} and hostname = {{ hostname }}"

- include_tasks: remove_nodjs_push-server.yml
  when: "manage == 'remove_nodjs' and inventory_hostname == hostname and (push_server_configure_web | bool)"

- include_tasks: remove_nodjs_push-server.yml
  when: "manage == 'configure_nodejs' and inventory_hostname == push_server and (push_server_configure_web | bool)"

- include_tasks: configure_nodjs_push-server.yml
  when: "manage == 'configure_nodejs' and inventory_hostname == hostname"
